### Login
# @name login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@imdbclone.com",
  "password": "parolasecreta123"
}

@authToken = Bearer {{login.response.body.token}}

### Current User Profile
# @name currentUser
GET http://localhost:8080/api/auth/me
Authorization: {{authToken}}

@userId = {{currentUser.response.body.id}}

### Change Password
PUT http://localhost:8080/api/auth/change-password
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "oldPassword": "parolasecreta123",
  "newPassword": "parolanoua456"
}

### Create a movie
# @name createMovie
POST http://localhost:8080/api/movies
Content-Type: application/json
Authorization: {{authToken}}

{
  "title": "The Matrix",
  "genre": "Action",
  "releaseYear": 2000
}

### Create another movie
# @name createAnotherMovie
POST http://localhost:8080/api/movies
Content-Type: application/json
Authorization: {{authToken}}

{
  "title": "Pulp Fiction",
  "genre": "Drama",
  "releaseYear": 1994
}


### Get all movies
GET http://localhost:8080/api/movies
Authorization: {{authToken}}

### Get movie by ID
GET http://localhost:8080/api/movies/{{createMovie.response.body.id}}
Authorization: {{authToken}}

### Edit movie by ID
PUT http://localhost:8080/api/movies/{{createMovie.response.body.id}}
Content-Type: application/json
Authorization: {{authToken}}

{
  "title": "The Matrix",
  "genre": "Action",
  "releaseYear": 1999
}

### Delete movie
DELETE http://localhost:8080/api/movies/{{createAnotherMovie.response.body.id}}
Authorization: {{authToken}}

### Search movies by title
GET http://localhost:8080/api/movies/search/title?title=matrix
Authorization: {{authToken}}

### Search movies by genre
GET http://localhost:8080/api/movies/search/genre?genre=Action
Authorization: {{authToken}}

### Search movies by year
GET http://localhost:8080/api/movies/search/year?year=1999
Authorization: {{authToken}}

### Add rating to movie
POST http://localhost:8080/api/movies/{{createMovie.response.body.id}}/rating?userId={{userId}}
Content-Type: application/json
Authorization: {{authToken}}

{
  "rating": 9
}